setOption("ScaleConversions", true);
run("8-bit");
setAutoThreshold("Otsu dark no-reset");
//run("Threshold...");
setAutoThreshold("Otsu dark stack no-reset");
//setThreshold(85, 255);
setOption("BlackBackground", true);
run("Convert to Mask", "method=Otsu background=Dark black");
run("Median 3D...", "x=2 y=2 z=2");
run("Remove Outliers...", "radius=2 threshold=50 which=Bright stack");
run("Fill Holes", "stack");
run("Skeletonize (2D/3D)");
